spring.application.name=AirBnb

spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb_db
spring.datasource.username=postgres
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

server.servlet.context-path=/api/v1
server.port=8081


jwt.secretKey=a8sd6faihdfjkas2398789afhdskjasdfh87yhk3jha987sdf89aabsdf876
frontend.url=http://localhost:8081
stripe.secret.key=sk_test_51TPJaTJzvDNlEqa6YdIkGhNt5sYDHmC53CJN4jSNFxIin6VHN8OYk7VHdWuVPekZ09umF34o5w2zdCtGJaMQBclz00WvuA4viX

stripe.webhook.secret=whsec_fcf7f0d910d54c1947fd231ba0951d18df2d772a35395454ea3592dc5059dc41